### PR TITLE
rm trailing slash from etherscan link; was resulting in '//' in urls

### PR DESCRIPTION
**Pull request by gerrrg**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any new dependencies that are required for this change.

Etherscan URLs have double slashes. Ex:
* https://optimistic.etherscan.io//address/0x4200000000000000000000000000000000000006
* https://optimistic.etherscan.io//tx/0xa44695d5a7abc091e64cb3aa8ca092384a73e71e91c2b6f0b05bdec9a10b86a6

This extremely minor edit removes the trailing slash of the etherscan link.

Fixes # (issue)
n/a

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Other

## How should this be tested?

Please provide instructions so we can test. Please also list any relevant details for your test configuration.

- [ ] Check optimistic.etherscan.io urls for // when clicking etherscan arrows

## Checklist:

- [ ] I have performed a self-review of my own code
- [ ] I have commented my code where relevant, particularly in hard-to-understand areas
- [ ] My changes generate no new console warnings
- [ ] The base of this PR is `master` if hotfix, `develop` if not

### CODE REVIEW

**Comment by groninge01** [comment]
@gerrrg Can you switch this PR to go to the beethovenx-optimism branch?

**Comment by gerrrg** [comment]
@groninge01 just updated it 👍

**Comment by danielmkm** [comment]
Thank you kindly sir!!

**Comment by danielmkm** [comment]
It looks like when you switched the branch it created more changes than you intended gerrg

**Comment by groninge01** [comment]
> It looks like when you switched the branch it created more changes than you intended gerrg

Ah you probably branched from beethovenx-staging. Sorry I forgot to mention the Optimism deploy is in it's own 'hard' branch for the moment.

**Comment by gerrrg** [comment]
Whoops, you're totally right. Was just going fast and not paying attention -- hang tight

**Comment by gerrrg** [comment]
Closing in favor of [136](https://github.com/beethovenxfi/frontend-v2/pull/136)

**Pull request closed without merging**
